// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/rpc/micro-ci.proto

package micro_ci

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Step struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Condition       string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Variables       map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContinueOnError bool                   `protobuf:"varint,4,opt,name=continue_on_error,json=continueOnError,proto3" json:"continue_on_error,omitempty"`
	Script          string                 `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{0}
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Step) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Step) GetContinueOnError() bool {
	if x != nil {
		return x.ContinueOnError
	}
	return false
}

func (x *Step) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Condition     string                 `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Steps         []*Step                `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Job) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Job) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Job) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

// Message definitions
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FetchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchJobRequest) Reset() {
	*x = FetchJobRequest{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchJobRequest) ProtoMessage() {}

func (x *FetchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchJobRequest.ProtoReflect.Descriptor instead.
func (*FetchJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{6}
}

func (x *FetchJobRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type FetchJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchJobResponse) Reset() {
	*x = FetchJobResponse{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchJobResponse) ProtoMessage() {}

func (x *FetchJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchJobResponse.ProtoReflect.Descriptor instead.
func (*FetchJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{7}
}

func (x *FetchJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type UpdateJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobRunId      string                 `protobuf:"bytes,1,opt,name=job_run_id,json=jobRunId,proto3" json:"job_run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusRequest) Reset() {
	*x = UpdateJobStatusRequest{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusRequest) ProtoMessage() {}

func (x *UpdateJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateJobStatusRequest) GetJobRunId() string {
	if x != nil {
		return x.JobRunId
	}
	return ""
}

func (x *UpdateJobStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusResponse) Reset() {
	*x = UpdateJobStatusResponse{}
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusResponse) ProtoMessage() {}

func (x *UpdateJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_micro_ci_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_micro_ci_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateJobStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_rpc_micro_ci_proto protoreflect.FileDescriptor

const file_pkg_rpc_micro_ci_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/rpc/micro-ci.proto\x12\bmicro_ci\"\xf7\x01\n" +
	"\x04Step\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x12;\n" +
	"\tvariables\x18\x03 \x03(\v2\x1d.micro_ci.Step.VariablesEntryR\tvariables\x12*\n" +
	"\x11continue_on_error\x18\x04 \x01(\bR\x0fcontinueOnError\x12\x16\n" +
	"\x06script\x18\x05 \x01(\tR\x06script\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\x12:\n" +
	"\tvariables\x18\x04 \x03(\v2\x1c.micro_ci.Job.VariablesEntryR\tvariables\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12$\n" +
	"\x05steps\x18\x06 \x03(\v2\x0e.micro_ci.StepR\x05steps\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11UnregisterRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\".\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x0fFetchJobRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"3\n" +
	"\x10FetchJobResponse\x12\x1f\n" +
	"\x03job\x18\x01 \x01(\v2\r.micro_ci.JobR\x03job\"N\n" +
	"\x16UpdateJobStatusRequest\x12\x1c\n" +
	"\n" +
	"job_run_id\x18\x01 \x01(\tR\bjobRunId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"3\n" +
	"\x17UpdateJobStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb0\x02\n" +
	"\aMicroCI\x12A\n" +
	"\bRegister\x12\x19.micro_ci.RegisterRequest\x1a\x1a.micro_ci.RegisterResponse\x12G\n" +
	"\n" +
	"Unregister\x12\x1b.micro_ci.UnregisterRequest\x1a\x1c.micro_ci.UnregisterResponse\x12A\n" +
	"\bFetchJob\x12\x19.micro_ci.FetchJobRequest\x1a\x1a.micro_ci.FetchJobResponse\x12V\n" +
	"\x0fUpdateJobStatus\x12 .micro_ci.UpdateJobStatusRequest\x1a!.micro_ci.UpdateJobStatusResponseB\x12Z\x10pkg/rpc/micro_cib\x06proto3"

var (
	file_pkg_rpc_micro_ci_proto_rawDescOnce sync.Once
	file_pkg_rpc_micro_ci_proto_rawDescData []byte
)

func file_pkg_rpc_micro_ci_proto_rawDescGZIP() []byte {
	file_pkg_rpc_micro_ci_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_micro_ci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_micro_ci_proto_rawDesc), len(file_pkg_rpc_micro_ci_proto_rawDesc)))
	})
	return file_pkg_rpc_micro_ci_proto_rawDescData
}

var file_pkg_rpc_micro_ci_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_rpc_micro_ci_proto_goTypes = []any{
	(*Step)(nil),                    // 0: micro_ci.Step
	(*Job)(nil),                     // 1: micro_ci.Job
	(*RegisterRequest)(nil),         // 2: micro_ci.RegisterRequest
	(*RegisterResponse)(nil),        // 3: micro_ci.RegisterResponse
	(*UnregisterRequest)(nil),       // 4: micro_ci.UnregisterRequest
	(*UnregisterResponse)(nil),      // 5: micro_ci.UnregisterResponse
	(*FetchJobRequest)(nil),         // 6: micro_ci.FetchJobRequest
	(*FetchJobResponse)(nil),        // 7: micro_ci.FetchJobResponse
	(*UpdateJobStatusRequest)(nil),  // 8: micro_ci.UpdateJobStatusRequest
	(*UpdateJobStatusResponse)(nil), // 9: micro_ci.UpdateJobStatusResponse
	nil,                             // 10: micro_ci.Step.VariablesEntry
	nil,                             // 11: micro_ci.Job.VariablesEntry
}
var file_pkg_rpc_micro_ci_proto_depIdxs = []int32{
	10, // 0: micro_ci.Step.variables:type_name -> micro_ci.Step.VariablesEntry
	11, // 1: micro_ci.Job.variables:type_name -> micro_ci.Job.VariablesEntry
	0,  // 2: micro_ci.Job.steps:type_name -> micro_ci.Step
	1,  // 3: micro_ci.FetchJobResponse.job:type_name -> micro_ci.Job
	2,  // 4: micro_ci.MicroCI.Register:input_type -> micro_ci.RegisterRequest
	4,  // 5: micro_ci.MicroCI.Unregister:input_type -> micro_ci.UnregisterRequest
	6,  // 6: micro_ci.MicroCI.FetchJob:input_type -> micro_ci.FetchJobRequest
	8,  // 7: micro_ci.MicroCI.UpdateJobStatus:input_type -> micro_ci.UpdateJobStatusRequest
	3,  // 8: micro_ci.MicroCI.Register:output_type -> micro_ci.RegisterResponse
	5,  // 9: micro_ci.MicroCI.Unregister:output_type -> micro_ci.UnregisterResponse
	7,  // 10: micro_ci.MicroCI.FetchJob:output_type -> micro_ci.FetchJobResponse
	9,  // 11: micro_ci.MicroCI.UpdateJobStatus:output_type -> micro_ci.UpdateJobStatusResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_rpc_micro_ci_proto_init() }
func file_pkg_rpc_micro_ci_proto_init() {
	if File_pkg_rpc_micro_ci_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_micro_ci_proto_rawDesc), len(file_pkg_rpc_micro_ci_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_micro_ci_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_micro_ci_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_micro_ci_proto_msgTypes,
	}.Build()
	File_pkg_rpc_micro_ci_proto = out.File
	file_pkg_rpc_micro_ci_proto_goTypes = nil
	file_pkg_rpc_micro_ci_proto_depIdxs = nil
}
