name: Micro CI Pipeline Test Local

variables:
  GO_ENV: development
  APP_VERSION: 1.0.0

jobs:
  - job: Micro CI Pipeline Test Job
    image: golang:1.21-alpine
    variables:
      JOB_1_VAR: job1-tester
    steps:
      - name: Display Message
        script: |
          echo "Running Micro CI Pipeline Test"

      - name: Project directory files
        script: |
          echo "Listing project directory files"
          ls

      - name: Failure Step Example
        continueOnError: true
        script: |
          echo "This pipeline should not exit due to a bash script failure
          asdfkjkqek ;k;kl

  - job: Second Job in Pipeline
    image: alpine:latest
    variables:
      JOB_2_VAR: job2-tester
    steps:
      - name: Display Message from Second Job
        script: |
          echo "This is the second job in the Micro CI Pipeline Test"

      - name: Show Local Variales and Environment Variables
        variables:
          LOCAL_VAR: tester
        script: |
          echo "Local Variable: $LOCAL_VAR"
          echo "Environment Variable GO_ENV: $GO_ENV"
          echo "Environment Variable APP_VERSION: $APP_VERSION"

      - name: Try Show Local Variable in another step
        script: |
          echo "Trying to access LOCAL_VAR from previous step: $LOCAL_VAR"
          echo "Job Variable JOB_1_VAR: $JOB_1_VAR"
          echo "Job Variable JOB_2_VAR: $JOB_2_VAR"